name: BariaHQMod
main: me.bariahq.bariahqmod.BariaHQMod
version: 2.0
description: Plugin for BariaHQ.
depend: [Aero]
softdepend: [BukkitTelnet, Essentials, LibsDisguises, WorldEdit]
authors: [Madgeek1450, Prozza, CreeperSeth, AwesomePinch, aggelosQQ, RobinGall2910, _Fleek_]
