name: UnraveledMCMod
main: me.unraveledmc.unraveledmcmod.UnraveledMCMod
version: 2.1
description: Plugin for the UnraveledMC server.
depend: [Aero, WorldEdit]
softdepend: [BukkitTelnet, UMC-Essentials, LibsDisguises, DiscordSRV]
authors: [Madgeek1450, Prozza, CreeperSeth, AwesomePinch, aggelosQQ, RobinGall2910]

# plugin.yml is no longer used to define commands.
