name: BariaHQMod
main: me.bariahq.bariahqmod.BariaHQMod
version: 2.0
description: Plugin for the UnraveledMC server.
depend: [Aero]
softdepend: [BukkitTelnet, UMC-Essentials, LibsDisguises, WorldEdit]
authors: [Madgeek1450, Prozza, CreeperSeth, AwesomePinch, aggelosQQ, RobinGall2910]
