name: UnraveledMCMod
main: me.unraveledmc.unraveledmcmod.UnraveledMCMod
version: 2.0
description: Plugin for the UnraveledMC server.
depend: [Aero, WorldEdit]
softdepend: [BukkitTelnet, UMC-Essentials, LibsDisguises]
authors: [Madgeek1450, Prozza, CreeperSeth, AwesomePinch, aggelosQQ]

# plugin.yml is no longer used to define commands.
