name: UnraveledMCMod
main: me.unraveledmc.unraveledmcmod.UnraveledMCMod
# This version is the base version. Ex 1.0 2.0 3.0 etc
version: 2.0
description: Plugin for the UnraveledMC server.
depend: [Aero, WorldEdit]
softdepend: [BukkitTelnet, UMC-Essentials, LibsDisguises, DiscordSRV]
authors: [Madgeek1450, Prozza, CreeperSeth, AwesomePinch, aggelosQQ, RobinGall2910]

# plugin.yml is no longer used to define commands.
